# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-BooK-Is-My-Bitch
version:      0.01
version_from: lib/Acme/BooK/Is/My/Bitch.pm
installdirs:  site
requires:
    Acme::MetaSyntactic:           0.89

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
